site_name: pycalrissian
site_description: 'Python client for Calrissian'
# Repository

repo_name: 'terradue/pycalrissian'
repo_url: 'http://github.com/terradue/pycalrissian'
edit_uri: 'blob/main/docs/src/'
site_url: 'https://terradue.github.io/pycalrissian/'


theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - mkdocs-jupyter

nav:
  - Introduction: 'index.md'
  - Installation: 'installation.md'
  - Getting started: 'gettingstarted.ipynb'
  - API:
    - pycalrissian.CalrissianContext : api/pycalrissian/context.md
    - pycalrissian.CalrissianJob : api/pycalrissian/job.md
    - pycalrissian.ExecutionJob : api/pycalrissian/execution.md
