name: env_calrissian
channels:
  - terradue
  - conda-forge
dependencies:
  - click
  - black
  - pre-commit
  - isort
  - flake8
  - autoflake
  - pylint
  - nose2
  - cwltool
  - pyyaml
  - pip:
    - kubernetes
